# Generated by Django 5.0.6 on 2024-05-29 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('full_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committed', models.CharField(max_length=100)),
                ('degree', models.CharField(choices=[('FELONY', 'Felony'), ('MISDOM', 'Misdomeanor')], default='MISDOM', max_length=6)),
                ('class_s', models.PositiveSmallIntegerField()),
                ('criminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crimdb.criminal')),
            ],
        ),
    ]
