# Generated by Django 5.0.7 on 2024-07-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminal',
            name='full_name',
            field=models.CharField(max_length=301),
        ),
    ]
